"""LLMInfra: attention, positional encoding, MoE and model building blocks.

The package is organized into subpackages by role:

- `attention`: classic, sparse, linear and hybrid attention variants
- `flash_attention`: educational FlashAttention v1-v4 implementations
- `positional`: absolute, relative, rotary and long-context position encodings
- `layers`: FFN / norm / SSM / transformer block layers
- `moe`: Mixture-of-Experts components
- `inference`: KV cache, paging and offload utilities
- `models`: encoder, decoder, language and multimodal models
- `speculative_decoding`: N-Gram, EAGLE, Medusa, MTP and DSpark decoding

`quantization` provides fake-quantization/QAT wrappers and
`module_registry` the public `build_*` / `list_*` factories.

All public names are re-exported here, so ``from llminfra import X`` works
regardless of the internal layout.
"""

from .attention import (
    ALiBiAttention,
    AttentionResidual,
    BaseAttention,
    BlockSparseAttention,
    CompressedSparseAttention,
    DynamicSparseAttention,
    FlashMLA,
    GatedDeltaNet,
    GroupedQueryAttention,
    HierarchicalCompressedAttention,
    HybridAttention,
    KimiDeltaAttention,
    LightningAttention,
    LinearAttention,
    MiniMaxSparseAttention,
    MultiHeadAttention,
    MultiHeadLatentAttention,
    MultiQueryAttention,
    QueryKeyBlockIndexer,
    RingAttention,
    SlidingWindowAttention,
    distributed_ring_attention,
    ring_attention,
)
from .flash_attention import FlashAttention, flash_attention
from .inference import (
    BlockSparseIndexer,
    OnDiskKVStore,
    PagedAttentionCache,
    PagedKVBlockAllocator,
    TieredKVCache,
    paged_attention,
)
from .layers import (
    ACTIVATIONS,
    ClampedSwiGLUFFN,
    DeepNorm,
    FeedForward,
    GeGLUFFN,
    HybridLayerStack,
    HybridSSMBlock,
    LayerNorm,
    LayerScale,
    Mamba2Layer,
    Mamba2State,
    ManifoldConstrainedHyperConnection,
    ReGLUFFN,
    RMSNorm,
    SwiGLUFFN,
    TransformerBlock,
    build_feed_forward,
    get_activation,
)
from .models import (
    CausalLMModel,
    CausalLMOutput,
    CrossAttention,
    CrossAttentionFuser,
    DecoderBlock,
    EmbeddingHead,
    EncoderBlock,
    EncoderDecoderModel,
    EncoderOnlyModel,
    EncoderOutput,
    MultimodalCausalLM,
    MultimodalCausalLMOutput,
    PrefixLMModel,
    RewardModelHead,
    SequenceClassificationHead,
    TokenClassificationHead,
    VisionEncoderAdapter,
    build_multimodal_position_ids,
    pool_hidden_state,
)
from .module_registry import build_attention, list_attentions
from .moe import (
    DeepSeekMoE,
    ExpertChoiceRouter,
    ExpertFFN,
    ExpertParallelMoE,
    LatentMoE,
    MixtureOfExperts,
    TopKRouter,
    load_balance_loss,
    router_z_loss,
)
from .positional import (
    LONGROPE_PRESETS,
    ALiBiBias,
    DynamicNTKRotaryEmbedding,
    LearnedAbsolutePositionEmbedding,
    LongRoPEPreset,
    LongRoPEScaledRotaryEmbedding,
    MultiModalRotaryPositionEmbedding,
    NoPositionEncoding,
    PartialRotaryPositionEmbedding,
    PositionInterpolation,
    RotaryPositionEmbedding,
    SinusoidalPositionEmbedding,
    T5RelativePositionBias,
    TwoDimensionalPositionEmbedding,
    YaRNParameters,
    YaRNScaledRotaryEmbedding,
    apply_rotary_pos_emb,
    build_positional_encoding,
    get_longrope_preset,
    list_positional_encodings,
    register_longrope_preset,
)
from .quantization import (
    FakeQuantizer,
    QATWrapper,
    QuantizationConfig,
    build_quantized,
)
from .speculative_decoding import (
    BlockDiffusionDrafter,
    DFlashDecoder,
    DSparkDecoder,
    DSparkScheduler,
    Eagle1Speculator,
    Eagle2Speculator,
    Eagle3Speculator,
    EagleSpeculator,
    MedusaHead,
    MTPDecoder,
    MultiTokenPredictionHead,
    NGramSpeculator,
    SpeculativeDecoder,
    dflash_loss,
    medusa_loss,
    mtp_loss,
)

__all__ = [
    "ACTIVATIONS",
    "LONGROPE_PRESETS",
    "ALiBiAttention",
    "ALiBiBias",
    "AttentionResidual",
    "BaseAttention",
    "BlockDiffusionDrafter",
    "BlockSparseAttention",
    "BlockSparseIndexer",
    "CausalLMModel",
    "CausalLMOutput",
    "ClampedSwiGLUFFN",
    "CompressedSparseAttention",
    "CrossAttention",
    "CrossAttentionFuser",
    "DFlashDecoder",
    "DSparkDecoder",
    "DSparkScheduler",
    "DecoderBlock",
    "DeepNorm",
    "DeepSeekMoE",
    "DynamicNTKRotaryEmbedding",
    "DynamicSparseAttention",
    "Eagle1Speculator",
    "Eagle2Speculator",
    "Eagle3Speculator",
    "EagleSpeculator",
    "EmbeddingHead",
    "EncoderBlock",
    "EncoderDecoderModel",
    "EncoderOnlyModel",
    "EncoderOutput",
    "ExpertChoiceRouter",
    "ExpertFFN",
    "ExpertParallelMoE",
    "FakeQuantizer",
    "FeedForward",
    "FlashAttention",
    "FlashMLA",
    "GatedDeltaNet",
    "GeGLUFFN",
    "GroupedQueryAttention",
    "HierarchicalCompressedAttention",
    "HybridAttention",
    "HybridLayerStack",
    "HybridSSMBlock",
    "KimiDeltaAttention",
    "LatentMoE",
    "LayerNorm",
    "LayerScale",
    "LearnedAbsolutePositionEmbedding",
    "LightningAttention",
    "LinearAttention",
    "LongRoPEPreset",
    "LongRoPEScaledRotaryEmbedding",
    "MTPDecoder",
    "Mamba2Layer",
    "Mamba2State",
    "ManifoldConstrainedHyperConnection",
    "MedusaHead",
    "MiniMaxSparseAttention",
    "MixtureOfExperts",
    "MultiHeadAttention",
    "MultiHeadLatentAttention",
    "MultiModalRotaryPositionEmbedding",
    "MultiQueryAttention",
    "MultiTokenPredictionHead",
    "MultimodalCausalLM",
    "MultimodalCausalLMOutput",
    "NGramSpeculator",
    "NoPositionEncoding",
    "OnDiskKVStore",
    "PagedAttentionCache",
    "PagedKVBlockAllocator",
    "PartialRotaryPositionEmbedding",
    "PositionInterpolation",
    "PrefixLMModel",
    "QATWrapper",
    "QuantizationConfig",
    "QueryKeyBlockIndexer",
    "RMSNorm",
    "ReGLUFFN",
    "RewardModelHead",
    "RingAttention",
    "RotaryPositionEmbedding",
    "SequenceClassificationHead",
    "SinusoidalPositionEmbedding",
    "SlidingWindowAttention",
    "SpeculativeDecoder",
    "SwiGLUFFN",
    "T5RelativePositionBias",
    "TieredKVCache",
    "TokenClassificationHead",
    "TopKRouter",
    "TransformerBlock",
    "TwoDimensionalPositionEmbedding",
    "VisionEncoderAdapter",
    "YaRNParameters",
    "YaRNScaledRotaryEmbedding",
    "apply_rotary_pos_emb",
    "build_attention",
    "build_feed_forward",
    "build_multimodal_position_ids",
    "build_positional_encoding",
    "build_quantized",
    "dflash_loss",
    "distributed_ring_attention",
    "flash_attention",
    "get_activation",
    "get_longrope_preset",
    "list_attentions",
    "list_positional_encodings",
    "load_balance_loss",
    "medusa_loss",
    "mtp_loss",
    "paged_attention",
    "pool_hidden_state",
    "register_longrope_preset",
    "ring_attention",
    "router_z_loss",
]
